language: perl6
perl6:
  - '2019.03'
  - '2018.10'
  - '2018.06'
  - '2018.04'
  - latest
matrix:
  allow_failures:
    - perl6: '2018.06'
    - perl6: '2018.04'
install:
  - rakudobrew build-zef
  - zef install --depsonly .
script:
  - prove -v -e "perl6 --ll-exception -Ilib" t
after_success:
  - zef list --installed --verbose
